<?php

namespace Database\Seeders;

use App\Models\Municipality;
use App\Models\State;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MunicipalitySeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $municipalities = [
            // Koshi Province (Province No. 1)
            // Sunsari District
            ['state_id' => 1, 'district_id' => 11, 'name' => 'Inaruwa Municipality'],
            ['state_id' => 1, 'district_id' => 11, 'name' => 'Dharan Sub-Metropolitan City'],
            ['state_id' => 1, 'district_id' => 11, 'name' => 'Itahari Sub-Metropolitan City'],
            ['state_id' => 1, 'district_id' => 11, 'name' => 'Barahachhetra Municipality'],
            ['state_id' => 1, 'district_id' => 11, 'name' => 'Bhokraha Municipality'],
            ['state_id' => 1, 'district_id' => 11, 'name' => 'Koshi Rural Municipality'],
            ['state_id' => 1, 'district_id' => 11, 'name' => 'Harinagara Rural Municipality'],
            ['state_id' => 1, 'district_id' => 11, 'name' => 'Gadhi Rural Municipality'],
            ['state_id' => 1, 'district_id' => 11, 'name' => 'Dewangan Rural Municipality'],
            ['state_id' => 1, 'district_id' => 11, 'name' => 'Panchakanya Rural Municipality'],
            ['state_id' => 1, 'district_id' => 11, 'name' => 'Ramdhuni Municipality'],
            ['state_id' => 1, 'district_id' => 11, 'name' => 'Barju Rural Municipality'],

            // Udayapur District
            ['state_id' => 1, 'district_id' => 14, 'name' => 'Triyuga Municipality'],
            ['state_id' => 1, 'district_id' => 14, 'name' => 'Katari Municipality'],
            ['state_id' => 1, 'district_id' => 14, 'name' => 'Belaka Municipality'],
            ['state_id' => 1, 'district_id' => 14, 'name' => 'Rautamai Rural Municipality'],
            ['state_id' => 1, 'district_id' => 14, 'name' => 'Limbuwakot Rural Municipality'],
            ['state_id' => 1, 'district_id' => 14, 'name' => 'Tapli Rural Municipality'],
            ['state_id' => 1, 'district_id' => 14, 'name' => 'Chaudandigadhi Municipality'],
            ['state_id' => 1, 'district_id' => 14, 'name' => 'Shivasatakshi Municipality'],
            ['state_id' => 1, 'district_id' => 14, 'name' => 'Udayapurgadhi Rural Municipality'],
            ['state_id' => 1, 'district_id' => 14, 'name' => 'Jogidaha Rural Municipality'],
            ['state_id' => 1, 'district_id' => 14, 'name' => 'Bhulke Rural Municipality'],
            ['state_id' => 1, 'district_id' => 14, 'name' => 'Halesi Tuwachung Municipality'],

            // Khotang District
            ['state_id' => 1, 'district_id' => 5, 'name' => 'Diktel Rupakota Majhuwagadhi'],
            ['state_id' => 1, 'district_id' => 5, 'name' => 'Sakela Rural Municipality'],
            ['state_id' => 1, 'district_id' => 5, 'name' => 'Aiselukharka Rural Municipality'],
            ['state_id' => 1, 'district_id' => 5, 'name' => 'Bhumlung Rural Municipality'],
            ['state_id' => 1, 'district_id' => 5, 'name' => 'Diprung Rural Municipality'],
            ['state_id' => 1, 'district_id' => 5, 'name' => 'Jantedhunga Rural Municipality'],
            ['state_id' => 1, 'district_id' => 5, 'name' => 'Kepilasgadhi Rural Municipality'],
            ['state_id' => 1, 'district_id' => 5, 'name' => 'Khemal Municipality'],
            ['state_id' => 1, 'district_id' => 5, 'name' => 'Marek Katahare Rural Municipality'],
            ['state_id' => 1, 'district_id' => 5, 'name' => 'Rawabesi Rural Municipality'],
            ['state_id' => 1, 'district_id' => 5, 'name' => 'Saune Rural Municipality'],
            ['state_id' => 1, 'district_id' => 5, 'name' => 'Tribeni Rural Municipality'],
            ['state_id' => 1, 'district_id' => 5, 'name' => 'Yamuna Rural Municipality'],

            // Okhaldhunga District
            ['state_id' => 1, 'district_id' => 7, 'name' => 'Siddhicharan Municipality'],
            ['state_id' => 1, 'district_id' => 7, 'name' => 'Molung Rural Municipality'],
            ['state_id' => 1, 'district_id' => 7, 'name' => 'Sunkoshi Rural Municipality'],
            ['state_id' => 1, 'district_id' => 7, 'name' => 'Khijikant Rural Municipality'],
            ['state_id' => 1, 'district_id' => 7, 'name' => 'Kunjo Rural Municipality'],
            ['state_id' => 1, 'district_id' => 7, 'name' => 'Madhavpur Rural Municipality'],
            ['state_id' => 1, 'district_id' => 7, 'name' => 'Mali Rural Municipality'],
            ['state_id' => 1, 'district_id' => 7, 'name' => 'Mandeepur Rural Municipality'],
            ['state_id' => 1, 'district_id' => 7, 'name' => 'Okhaldhunga Rural Municipality'],
            ['state_id' => 1, 'district_id' => 7, 'name' => 'Ragani Rural Municipality'],
            ['state_id' => 1, 'district_id' => 7, 'name' => 'Sidingwa Rural Municipality'],
            ['state_id' => 1, 'district_id' => 7, 'name' => 'Tarkali Rural Municipality'],
            ['state_id' => 1, 'district_id' => 7, 'name' => 'Thakle Rural Municipality'],

            // Panchthar District
            ['state_id' => 1, 'district_id' => 8, 'name' => 'Phidim Municipality'],
            ['state_id' => 1, 'district_id' => 8, 'name' => 'Ektin Rural Municipality'],
            ['state_id' => 1, 'district_id' => 8, 'name' => 'Falelung Rural Municipality'],
            ['state_id' => 1, 'district_id' => 8, 'name' => 'Hilihang Rural Municipality'],
            ['state_id' => 1, 'district_id' => 8, 'name' => 'Kummayak Rural Municipality'],
            ['state_id' => 1, 'district_id' => 8, 'name' => 'Miklajung Rural Municipality'],
            ['state_id' => 1, 'district_id' => 8, 'name' => 'Maiwakhola Rural Municipality'],
            ['state_id' => 1, 'district_id' => 8, 'name' => 'Phungling Municipality'],
            ['state_id' => 1, 'district_id' => 8, 'name' => 'Panchthar Rural Municipality'],
            ['state_id' => 1, 'district_id' => 8, 'name' => 'Yangwarak Rural Municipality'],
            ['state_id' => 1, 'district_id' => 8, 'name' => 'Tumbewa Rural Municipality'],
            ['state_id' => 1, 'district_id' => 8, 'name' => 'Yashok Rural Municipality'],

            // Terhathum District
            ['state_id' => 1, 'district_id' => 13, 'name' => 'Myanglung Municipality'],
            ['state_id' => 1, 'district_id' => 13, 'name' => 'Aathrai Rural Municipality'],
            ['state_id' => 1, 'district_id' => 13, 'name' => 'Chhathar Rural Municipality'],
            ['state_id' => 1, 'district_id' => 13, 'name' => 'Laligurash Municipality'],
            ['state_id' => 1, 'district_id' => 13, 'name' => 'Maijogmai Rural Municipality'],
            ['state_id' => 1, 'district_id' => 13, 'name' => 'Mekhligunj Rural Municipality'],
            ['state_id' => 1, 'district_id' => 13, 'name' => 'Sankranti Bazar Rural Municipality'],
            ['state_id' => 1, 'district_id' => 13, 'name' => 'Sabla Rural Municipality'],

            // Sankhuwasabha District
            ['state_id' => 1, 'district_id' => 9, 'name' => 'Khandbari Municipality'],
            ['state_id' => 1, 'district_id' => 9, 'name' => 'Bhotkhola Rural Municipality'],
            ['state_id' => 1, 'district_id' => 9, 'name' => 'Chichila Rural Municipality'],
            ['state_id' => 1, 'district_id' => 9, 'name' => 'Madi Rural Municipality'],
            ['state_id' => 1, 'district_id' => 9, 'name' => 'Makalu Rural Municipality'],
            ['state_id' => 1, 'district_id' => 9, 'name' => 'Mangtewa Rural Municipality'],
            ['state_id' => 1, 'district_id' => 9, 'name' => 'Panchakharp Rural Municipality'],
            ['state_id' => 1, 'district_id' => 9, 'name' => 'Pakhribas Rural Municipality'],
            ['state_id' => 1, 'district_id' => 9, 'name' => 'Tumlingtar Municipality'],
            ['state_id' => 1, 'district_id' => 9, 'name' => 'Chainpur Rural Municipality'],
            ['state_id' => 1, 'district_id' => 9, 'name' => 'Siddhapokhari Rural Municipality'],
            ['state_id' => 1, 'district_id' => 9, 'name' => 'Sankhuwasabha Rural Municipality'],
            ['state_id' => 1, 'district_id' => 9, 'name' => 'Silichong Rural Municipality'],

            // Solukhumbu District
            ['state_id' => 1, 'district_id' => 10, 'name' => 'Solukhumbu Municipality'],
            ['state_id' => 1, 'district_id' => 10, 'name' => 'Sotang Rural Municipality'],
            ['state_id' => 1, 'district_id' => 10, 'name' => 'Thulung Dudhkoshi Rural Municipality'],
            ['state_id' => 1, 'district_id' => 10, 'name' => 'Mahakulung Rural Municipality'],
            ['state_id' => 1, 'district_id' => 10, 'name' => 'Nechasalyan Rural Municipality'],
            ['state_id' => 1, 'district_id' => 10, 'name' => 'Likhu Pike Rural Municipality'],
            ['state_id' => 1, 'district_id' => 10, 'name' => 'Khote-Rangas Rural Municipality'],
            ['state_id' => 1, 'district_id' => 10, 'name' => 'Jubu Rural Municipality'],
            ['state_id' => 1, 'district_id' => 10, 'name' => 'Khumbu Pasang Lhamu Rural Municipality'],
            
            // Dhankuta District
            ['state_id' => 1, 'district_id' => 2, 'name' => 'Dhankuta Municipality'],
            ['state_id' => 1, 'district_id' => 2, 'name' => 'Chhathar Jorpati Rural Municipality'],
            ['state_id' => 1, 'district_id' => 2, 'name' => 'Mahadeva Rural Municipality'],
            ['state_id' => 1, 'district_id' => 2, 'name' => 'Sahid Smarak Rural Municipality'],
            ['state_id' => 1, 'district_id' => 2, 'name' => 'Maiwakhola Rural Municipality'],
            ['state_id' => 1, 'district_id' => 2, 'name' => 'Mundum Bahumati Rural Municipality'],
            
            // Ilam District
            ['state_id' => 1, 'district_id' => 3, 'name' => 'Ilam Municipality'],
            ['state_id' => 1, 'district_id' => 3, 'name' => 'Mechinagar Municipality'],
            ['state_id' => 1, 'district_id' => 3, 'name' => 'Mai Municipality'],
            ['state_id' => 1, 'district_id' => 3, 'name' => 'Suryodaya Municipality'],
            ['state_id' => 1, 'district_id' => 3, 'name' => 'Deumai Municipality'],
            ['state_id' => 1, 'district_id' => 3, 'name' => 'Sandakpur Rural Municipality'],
            ['state_id' => 1, 'district_id' => 3, 'name' => 'Maijogmai Rural Municipality'],
            ['state_id' => 1, 'district_id' => 3, 'name' => 'Shree Antu Rural Municipality'],
            ['state_id' => 1, 'district_id' => 3, 'name' => 'Chulachuli Rural Municipality'],
            ['state_id' => 1, 'district_id' => 3, 'name' => 'Rong Rural Municipality'],
            
            // Jhapa District
            ['state_id' => 1, 'district_id' => 4, 'name' => 'Mechinagar Municipality'],
            ['state_id' => 1, 'district_id' => 4, 'name' => 'Birtamod Municipality'],
            ['state_id' => 1, 'district_id' => 4, 'name' => 'Kankai Municipality'],
            ['state_id' => 1, 'district_id' => 4, 'name' => 'Arjundhara Municipality'],
            ['state_id' => 1, 'district_id' => 4, 'name' => 'Bhadrapur Municipality'],
            ['state_id' => 1, 'district_id' => 4, 'name' => 'Kachankawal Rural Municipality'],
            ['state_id' => 1, 'district_id' => 4, 'name' => 'Haldibari Rural Municipality'],
            ['state_id' => 1, 'district_id' => 4, 'name' => 'Shivasatakshi Municipality'],
            ['state_id' => 1, 'district_id' => 4, 'name' => 'Gauradaha Municipality'],
            ['state_id' => 1, 'district_id' => 4, 'name' => 'Gaurigadh Rural Municipality'],
            ['state_id' => 1, 'district_id' => 4, 'name' => 'Jhapa Rural Municipality'],
            ['state_id' => 1, 'district_id' => 4, 'name' => 'Kamal Rural Municipality'],
            ['state_id' => 1, 'district_id' => 4, 'name' => 'Pathari Shanishchare Municipality'],
            ['state_id' => 1, 'district_id' => 4, 'name' => 'Buddhashanti Rural Municipality'],
            ['state_id' => 1, 'district_id' => 4, 'name' => 'Damak Municipality'],
            ['state_id' => 1, 'district_id' => 4, 'name' => 'Baharangi Rural Municipality'],
            
            // Morang District
            ['state_id' => 1, 'district_id' => 6, 'name' => 'Biratnagar Metropolitan City'],
            ['state_id' => 1, 'district_id' => 6, 'name' => 'Urlabari Municipality'],
            ['state_id' => 1, 'district_id' => 6, 'name' => 'Rangeli Municipality'],
            ['state_id' => 1, 'district_id' => 6, 'name' => 'Sundar Haraicha Municipality'],
            ['state_id' => 1, 'district_id' => 6, 'name' => 'Kerabari Rural Municipality'],
            ['state_id' => 1, 'district_id' => 6, 'name' => 'Katahari Rural Municipality'],
            ['state_id' => 1, 'district_id' => 6, 'name' => 'Letang Municipality'],
            ['state_id' => 1, 'district_id' => 6, 'name' => 'Belbari Municipality'],
            ['state_id' => 1, 'district_id' => 6, 'name' => 'Sunawarshi Municipality'],
            ['state_id' => 1, 'district_id' => 6, 'name' => 'Ratuwamai Municipality'],
            ['state_id' => 1, 'district_id' => 6, 'name' => 'Gramthan Rural Municipality'],
            ['state_id' => 1, 'district_id' => 6, 'name' => 'Miklajung Rural Municipality'],
            ['state_id' => 1, 'district_id' => 6, 'name' => 'Dhanpalthan Rural Municipality'],
            ['state_id' => 1, 'district_id' => 6, 'name' => 'Budhiganga Rural Municipality'],
            ['state_id' => 1, 'district_id' => 6, 'name' => 'Jahada Rural Municipality'],
            ['state_id' => 1, 'district_id' => 6, 'name' => 'Kanepokhari Rural Municipality'],
            ['state_id' => 1, 'district_id' => 6, 'name' => 'Bhogateni Rural Municipality'],
            
            // Madhesh Province (Province No. 2)
            // Bara District
            ['state_id' => 2, 'district_id' => 15, 'name' => 'Kalaiya Sub-Metropolitan City'],
            ['state_id' => 2, 'district_id' => 15, 'name' => 'Jitpur Simara Sub-Metropolitan City'],
            ['state_id' => 2, 'district_id' => 15, 'name' => 'Nijgadh Municipality'],
            ['state_id' => 2, 'district_id' => 15, 'name' => 'Mahagadhimai Municipality'],
            ['state_id' => 2, 'district_id' => 15, 'name' => 'Suwarna Rural Municipality'],
            ['state_id' => 2, 'district_id' => 15, 'name' => 'Prasauni Rural Municipality'],
            ['state_id' => 2, 'district_id' => 15, 'name' => 'Debahi Chhara Rural Municipality'],
            ['state_id' => 2, 'district_id' => 15, 'name' => 'Parwanipur Rural Municipality'],
            ['state_id' => 2, 'district_id' => 15, 'name' => 'Pheta Rural Municipality'],
            ['state_id' => 2, 'district_id' => 15, 'name' => 'Bishrampur Rural Municipality'],
            ['state_id' => 2, 'district_id' => 15, 'name' => 'Madhav Narayan Rural Municipality'],
            ['state_id' => 2, 'district_id' => 15, 'name' => 'Kabilasi Rural Municipality'],
            ['state_id' => 2, 'district_id' => 15, 'name' => 'Brindaban Rural Municipality'],
            ['state_id' => 2, 'district_id' => 15, 'name' => 'Karaiya Rural Municipality'],
            ['state_id' => 2, 'district_id' => 15, 'name' => 'Pachrauta Rural Municipality'],
            ['state_id' => 2, 'district_id' => 15, 'name' => 'Simraungadh Rural Municipality'],
            ['state_id' => 2, 'district_id' => 15, 'name' => 'Chakragatti Rural Municipality'],

            // Dhanusha District
            ['state_id' => 2, 'district_id' => 16, 'name' => 'Janakpur Sub-Metropolitan City'],
            ['state_id' => 2, 'district_id' => 16, 'name' => 'Bhanpur Rural Municipality'],
            ['state_id' => 2, 'district_id' => 16, 'name' => 'Bishnupur Rural Municipality'],
            ['state_id' => 2, 'district_id' => 16, 'name' => 'Chakka Rural Municipality'],
            ['state_id' => 2, 'district_id' => 16, 'name' => 'Dhanauj Rural Municipality'],
            ['state_id' => 2, 'district_id' => 16, 'name' => 'Ganeshpur Rural Municipality'],
            ['state_id' => 2, 'district_id' => 16, 'name' => 'Hansapur Rural Municipality'],
            ['state_id' => 2, 'district_id' => 16, 'name' => 'Janakradha Rural Municipality'],
            ['state_id' => 2, 'district_id' => 16, 'name' => 'Kamala Rural Municipality'],
            ['state_id' => 2, 'district_id' => 16, 'name' => 'Mukhiyapatti Mushargiya Rural Municipality'],
            ['state_id' => 2, 'district_id' => 16, 'name' => 'Sahidnagar Rural Municipality'],
            ['state_id' => 2, 'district_id' => 16, 'name' => 'Sabaila Rural Municipality'],
            ['state_id' => 2, 'district_id' => 16, 'name' => 'Tilathi Rural Municipality'],
            ['state_id' => 2, 'district_id' => 16, 'name' => 'Aurahi Rural Municipality'],

            // Mahottari District
            ['state_id' => 2, 'district_id' => 17, 'name' => 'Jaleshwor Municipality'],
            ['state_id' => 2, 'district_id' => 17, 'name' => 'Bhangaha Rural Municipality'],
            ['state_id' => 2, 'district_id' => 17, 'name' => 'Bardibas Rural Municipality'],
            ['state_id' => 2, 'district_id' => 17, 'name' => 'Bhramarpuri Rural Municipality'],
            ['state_id' => 2, 'district_id' => 17, 'name' => 'Ekarwa Rural Municipality'],
            ['state_id' => 2, 'district_id' => 17, 'name' => 'Gaushala Rural Municipality'],
            ['state_id' => 2, 'district_id' => 17, 'name' => 'Jaleshwor Rural Municipality'],
            ['state_id' => 2, 'district_id' => 17, 'name' => 'Loharpatti Rural Municipality'],
            ['state_id' => 2, 'district_id' => 17, 'name' => 'Mahottari Rural Municipality'],
            ['state_id' => 2, 'district_id' => 17, 'name' => 'Matihani Rural Municipality'],
            ['state_id' => 2, 'district_id' => 17, 'name' => 'Nauwakot Rural Municipality'],
            ['state_id' => 2, 'district_id' => 17, 'name' => 'Ramgadhiwa Rural Municipality'],
            ['state_id' => 2, 'district_id' => 17, 'name' => 'Samsi Rural Municipality'],
            ['state_id' => 2, 'district_id' => 17, 'name' => 'Shreepur Rural Municipality'],

            // Parsa District
            ['state_id' => 2, 'district_id' => 18, 'name' => 'Birgunj Metropolitan City'],
            ['state_id' => 2, 'district_id' => 18, 'name' => 'Bhaurahi Rural Municipality'],
            ['state_id' => 2, 'district_id' => 18, 'name' => 'Bindabasini Rural Municipality'],
            ['state_id' => 2, 'district_id' => 18, 'name' => 'Birgunj Rural Municipality'],
            ['state_id' => 2, 'district_id' => 18, 'name' => 'Chhathwa Rural Municipality'],
            ['state_id' => 2, 'district_id' => 18, 'name' => 'Jagarnathpur Rural Municipality'],
            ['state_id' => 2, 'district_id' => 18, 'name' => 'Jirabhawani Rural Municipality'],
            ['state_id' => 2, 'district_id' => 18, 'name' => 'Kalikamai Rural Municipality'],
            ['state_id' => 2, 'district_id' => 18, 'name' => 'Lahabati Rural Municipality'],
            ['state_id' => 2, 'district_id' => 18, 'name' => 'Lalbandi Rural Municipality'],
            ['state_id' => 2, 'district_id' => 18, 'name' => 'Parsagadhi Rural Municipality'],
            ['state_id' => 2, 'district_id' => 18, 'name' => 'Paterwa Sugauli Rural Municipality'],
            ['state_id' => 2, 'district_id' => 18, 'name' => 'Sahidnagar Rural Municipality'],
            ['state_id' => 2, 'district_id' => 18, 'name' => 'Sirsiya Rural Municipality'],
            ['state_id' => 2, 'district_id' => 18, 'name' => 'Thadi Rural Municipality'],
            ['state_id' => 2, 'district_id' => 18, 'name' => 'Bageshwori Rural Municipality'],
            ['state_id' => 2, 'district_id' => 18, 'name' => 'Pokhariya Municipality'],
            ['state_id' => 2, 'district_id' => 18, 'name' => 'Srivani Rural Municipality'],

            // Rautahat District
            ['state_id' => 2, 'district_id' => 19, 'name' => 'Gaur Municipality'],
            ['state_id' => 2, 'district_id' => 19, 'name' => 'Brindaban Rural Municipality'],
            ['state_id' => 2, 'district_id' => 19, 'name' => 'Chandrapur Rural Municipality'],
            ['state_id' => 2, 'district_id' => 19, 'name' => 'Dewahi Gonahi Rural Municipality'],
            ['state_id' => 2, 'district_id' => 19, 'name' => 'Durga Bhagawati Rural Municipality'],
            ['state_id' => 2, 'district_id' => 19, 'name' => 'Fatuwa Bijayapur Rural Municipality'],
            ['state_id' => 2, 'district_id' => 19, 'name' => 'Garuda Rural Municipality'],
            ['state_id' => 2, 'district_id' => 19, 'name' => 'Gujara Municipality'],
            ['state_id' => 2, 'district_id' => 19, 'name' => 'Ishwarpur Rural Municipality'],
            ['state_id' => 2, 'district_id' => 19, 'name' => 'Katahariya Municipality'],
            ['state_id' => 2, 'district_id' => 19, 'name' => 'Madhav Narayan Rural Municipality'],
            ['state_id' => 2, 'district_id' => 19, 'name' => 'Matiarwa Rural Municipality'],
            ['state_id' => 2, 'district_id' => 19, 'name' => 'Parsa Devi Rural Municipality'],
            ['state_id' => 2, 'district_id' => 19, 'name' => 'Pharwaha Rural Municipality'],
            ['state_id' => 2, 'district_id' => 19, 'name' => 'Rajdevi Rural Municipality'],
            ['state_id' => 2, 'district_id' => 19, 'name' => 'Rajpur Rural Municipality'],
            ['state_id' => 2, 'district_id' => 19, 'name' => 'Ramnagar Rural Municipality'],
            ['state_id' => 2, 'district_id' => 19, 'name' => 'Yoginimai Rural Municipality'],

            // Sarlahi District
            ['state_id' => 2, 'district_id' => 21, 'name' => 'Malangwa Municipality'],
            ['state_id' => 2, 'district_id' => 21, 'name' => 'Aishwarya Rural Municipality'],
            ['state_id' => 2, 'district_id' => 21, 'name' => 'Bagmati Rural Municipality'],
            ['state_id' => 2, 'district_id' => 21, 'name' => 'Balara Rural Municipality'],
            ['state_id' => 2, 'district_id' => 21, 'name' => 'Barahathwa Municipality'],
            ['state_id' => 2, 'district_id' => 21, 'name' => 'Brahmapuri Rural Municipality'],
            ['state_id' => 2, 'district_id' => 21, 'name' => 'Chakragadhi Rural Municipality'],
            ['state_id' => 2, 'district_id' => 21, 'name' => 'Dhankaul Rural Municipality'],
            ['state_id' => 2, 'district_id' => 21, 'name' => 'Godaita Municipality'],
            ['state_id' => 2, 'district_id' => 21, 'name' => 'Haripur Rural Municipality'],
            ['state_id' => 2, 'district_id' => 21, 'name' => 'Harion Municipality'],
            ['state_id' => 2, 'district_id' => 21, 'name' => 'Ishwarpur Rural Municipality'],
            ['state_id' => 2, 'district_id' => 21, 'name' => 'Kabilasi Rural Municipality'],
            ['state_id' => 2, 'district_id' => 21, 'name' => 'Lalbandi Rural Municipality'],
            ['state_id' => 2, 'district_id' => 21, 'name' => 'Laxmipur Rural Municipality'],
            ['state_id' => 2, 'district_id' => 21, 'name' => 'Parsa Rural Municipality'],
            ['state_id' => 2, 'district_id' => 21, 'name' => 'Ramnagar Rural Municipality'],
            ['state_id' => 2, 'district_id' => 21, 'name' => 'Salempur Rural Municipality'],
            ['state_id' => 2, 'district_id' => 21, 'name' => 'Sahodara Rural Municipality'],

            // Siraha District
            ['state_id' => 2, 'district_id' => 22, 'name' => 'Siraha Municipality'],
            ['state_id' => 2, 'district_id' => 22, 'name' => 'Arnama Rural Municipality'],
            ['state_id' => 2, 'district_id' => 22, 'name' => 'Bishnupur Rural Municipality'],
            ['state_id' => 2, 'district_id' => 22, 'name' => 'Bhagawanpur Rural Municipality'],
            ['state_id' => 2, 'district_id' => 22, 'name' => 'Bhogawa Rural Municipality'],
            ['state_id' => 2, 'district_id' => 22, 'name' => 'Dhanagadi Rural Municipality'],
            ['state_id' => 2, 'district_id' => 22, 'name' => 'Dhanauja Rural Municipality'],
            ['state_id' => 2, 'district_id' => 22, 'name' => 'Gadhimai Rural Municipality'],
            ['state_id' => 2, 'district_id' => 22, 'name' => 'Kalyanpur Rural Municipality'],
            ['state_id' => 2, 'district_id' => 22, 'name' => 'Karahi Rural Municipality'],
            ['state_id' => 2, 'district_id' => 22, 'name' => 'Lahan Municipality'],
            ['state_id' => 2, 'district_id' => 22, 'name' => 'Mithila Rural Municipality'],
            ['state_id' => 2, 'district_id' => 22, 'name' => 'Nawarajpur Rural Municipality'],
            ['state_id' => 2, 'district_id' => 22, 'name' => 'Sakhuwa Rural Municipality'],
            ['state_id' => 2, 'district_id' => 22, 'name' => 'Sukhipur Rural Municipality'],
            ['state_id' => 2, 'district_id' => 22, 'name' => 'Tarahi Rural Municipality'],
            ['state_id' => 2, 'district_id' => 22, 'name' => 'Golbazar Municipality'],
            ['state_id' => 2, 'district_id' => 22, 'name' => 'Mirchaiya Rural Municipality'],
            ['state_id' => 2, 'district_id' => 22, 'name' => 'Bishnupaduka Rural Municipality'],

            // Saptari District
            ['state_id' => 2, 'district_id' => 20, 'name' => 'Rajbiraj Municipality'],
            ['state_id' => 2, 'district_id' => 20, 'name' => 'Bishnupur Rural Municipality'],
            ['state_id' => 2, 'district_id' => 20, 'name' => 'Bodebarsain Rural Municipality'],
            ['state_id' => 2, 'district_id' => 20, 'name' => 'Chhinnamasta Rural Municipality'],
            ['state_id' => 2, 'district_id' => 20, 'name' => 'Dhanagadhi Rural Municipality'],
            ['state_id' => 2, 'district_id' => 20, 'name' => 'Fattepur Rural Municipality'],
            ['state_id' => 2, 'district_id' => 20, 'name' => 'Hanumannagar Kankalini Rural Municipality'],
            ['state_id' => 2, 'district_id' => 20, 'name' => 'Khadak Rural Municipality'],
            ['state_id' => 2, 'district_id' => 20, 'name' => 'Kishanpur Rural Municipality'],
            ['state_id' => 2, 'district_id' => 20, 'name' => 'Mahadeva Rural Municipality'],
            ['state_id' => 2, 'district_id' => 20, 'name' => 'Rajbiraj Rural Municipality'],
            ['state_id' => 2, 'district_id' => 20, 'name' => 'Ramaroshan Rural Municipality'],
            ['state_id' => 2, 'district_id' => 20, 'name' => 'Rupani Rural Municipality'],
            ['state_id' => 2, 'district_id' => 20, 'name' => 'Sambhunath Rural Municipality'],
            ['state_id' => 2, 'district_id' => 20, 'name' => 'Saraswor Rural Municipality'],
            ['state_id' => 2, 'district_id' => 20, 'name' => 'Surunga Municipality'],
            ['state_id' => 2, 'district_id' => 20, 'name' => 'Tilathi Rural Municipality'],
            ['state_id' => 2, 'district_id' => 20, 'name' => 'Tirhut Rural Municipality'],
            ['state_id' => 2, 'district_id' => 20, 'name' => 'Bhagawatpur Rural Municipality'],
            
            // Bagmati Province
            // Dhading District
            ['state_id' => 3, 'district_id' => 25, 'name' => 'Nilkantha Municipality'],
            ['state_id' => 3, 'district_id' => 25, 'name' => 'Benighat Rorang Rural Municipality'],
            ['state_id' => 3, 'district_id' => 25, 'name' => 'Gajuri Rural Municipality'],
            ['state_id' => 3, 'district_id' => 25, 'name' => 'Gorkha Rural Municipality'],
            ['state_id' => 3, 'district_id' => 25, 'name' => 'Jeevanpur Rural Municipality'],
            ['state_id' => 3, 'district_id' => 25, 'name' => 'Khadadevi Rural Municipality'],
            ['state_id' => 3, 'district_id' => 25, 'name' => 'Khaniyabas Rural Municipality'],
            ['state_id' => 3, 'district_id' => 25, 'name' => 'Netrawali Rural Municipality'],
            ['state_id' => 3, 'district_id' => 25, 'name' => 'Siddhalek Rural Municipality'],
            ['state_id' => 3, 'district_id' => 25, 'name' => 'Tangilbang Rural Municipality'],
            ['state_id' => 3, 'district_id' => 25, 'name' => 'Thakre Rural Municipality'],
            ['state_id' => 3, 'district_id' => 25, 'name' => 'Tripurasundari Rural Municipality'],

            // Dolakha District
            ['state_id' => 3, 'district_id' => 26, 'name' => 'Bhimeshwar Municipality'],
            ['state_id' => 3, 'district_id' => 26, 'name' => 'Baiteshwor Rural Municipality'],
            ['state_id' => 3, 'district_id' => 26, 'name' => 'Bhimtar Rural Municipality'],
            ['state_id' => 3, 'district_id' => 26, 'name' => 'Chankheli Rural Municipality'],
            ['state_id' => 3, 'district_id' => 26, 'name' => 'Chilankha Rural Municipality'],
            ['state_id' => 3, 'district_id' => 26, 'name' => 'Dolakha Rural Municipality'],
            ['state_id' => 3, 'district_id' => 26, 'name' => 'Gaurishankar Rural Municipality'],
            ['state_id' => 3, 'district_id' => 26, 'name' => 'Jiri Municipality'],
            ['state_id' => 3, 'district_id' => 26, 'name' => 'Kalinchowk Rural Municipality'],
            ['state_id' => 3, 'district_id' => 26, 'name' => 'Khadka Rural Municipality'],
            ['state_id' => 3, 'district_id' => 26, 'name' => 'Lamidanda Rural Municipality'],
            ['state_id' => 3, 'district_id' => 26, 'name' => 'Mai Pokhari Rural Municipality'],
            ['state_id' => 3, 'district_id' => 26, 'name' => 'Melung Rural Municipality'],
            ['state_id' => 3, 'district_id' => 26, 'name' => 'Sailung Rural Municipality'],
            ['state_id' => 3, 'district_id' => 26, 'name' => 'Sunakhani Rural Municipality'],
            ['state_id' => 3, 'district_id' => 26, 'name' => 'Tamakoshi Rural Municipality'],

            // Nuwakot District
            ['state_id' => 3, 'district_id' => 31, 'name' => 'Bidur Municipality'],
            ['state_id' => 3, 'district_id' => 31, 'name' => 'Belkotgadhi Rural Municipality'],
            ['state_id' => 3, 'district_id' => 31, 'name' => 'Bhimtang Rural Municipality'],
            ['state_id' => 3, 'district_id' => 31, 'name' => 'Dupcheshwar Rural Municipality'],
            ['state_id' => 3, 'district_id' => 31, 'name' => 'Kakani Rural Municipality'],
            ['state_id' => 3, 'district_id' => 31, 'name' => 'Kispang Rural Municipality'],
            ['state_id' => 3, 'district_id' => 31, 'name' => 'Likhu Rural Municipality'],
            ['state_id' => 3, 'district_id' => 31, 'name' => 'Mylang Rural Municipality'],
            ['state_id' => 3, 'district_id' => 31, 'name' => 'Panchkhal Rural Municipality'],
            ['state_id' => 3, 'district_id' => 31, 'name' => 'Rashad Rural Municipality'],
            ['state_id' => 3, 'district_id' => 31, 'name' => 'Shivapuri Rural Municipality'],
            ['state_id' => 3, 'district_id' => 31, 'name' => 'Suryagadhi Rural Municipality'],
            ['state_id' => 3, 'district_id' => 31, 'name' => 'Tadi Rural Municipality'],
            ['state_id' => 3, 'district_id' => 31, 'name' => 'Tarakeshwor Rural Municipality'],
            ['state_id' => 3, 'district_id' => 31, 'name' => 'Tadi Rural Municipality'],
            ['state_id' => 3, 'district_id' => 31, 'name' => 'Ugratara Kaliika Rural Municipality'],
            ['state_id' => 3, 'district_id' => 31, 'name' => 'Wunekot Rural Municipality'],

            // Rasuwa District
            ['state_id' => 3, 'district_id' => 32, 'name' => 'Uttargaya Rural Municipality'],
            ['state_id' => 3, 'district_id' => 32, 'name' => 'Aamachhodingmo Rural Municipality'],
            ['state_id' => 3, 'district_id' => 32, 'name' => 'Kalika Rural Municipality'],
            ['state_id' => 3, 'district_id' => 32, 'name' => 'Naukunda Rural Municipality'],
            ['state_id' => 3, 'district_id' => 32, 'name' => 'Parbatikunda Rural Municipality'],
            ['state_id' => 3, 'district_id' => 32, 'name' => 'Thulosirubari Rural Municipality'],

            // Ramechhap District
            ['state_id' => 3, 'district_id' => 33, 'name' => 'Manthali Municipality'],
            ['state_id' => 3, 'district_id' => 33, 'name' => 'Bhimchuli Rural Municipality'],
            ['state_id' => 3, 'district_id' => 33, 'name' => 'Bhatauliya Rural Municipality'],
            ['state_id' => 3, 'district_id' => 33, 'name' => 'Doramba Rural Municipality'],
            ['state_id' => 3, 'district_id' => 33, 'name' => 'Goganda Rural Municipality'],
            ['state_id' => 3, 'district_id' => 33, 'name' => 'Khadadevi Rural Municipality'],
            ['state_id' => 3, 'district_id' => 33, 'name' => 'Khimti Rural Municipality'],
            ['state_id' => 3, 'district_id' => 33, 'name' => 'Likhu Tamakoshi Rural Municipality'],
            ['state_id' => 3, 'district_id' => 33, 'name' => 'Madi Rural Municipality'],
            ['state_id' => 3, 'district_id' => 33, 'name' => 'Ramechhap Rural Municipality'],
            ['state_id' => 3, 'district_id' => 33, 'name' => 'Sunarpani Rural Municipality'],
            ['state_id' => 3, 'district_id' => 33, 'name' => 'Sukajor Rural Municipality'],
            ['state_id' => 3, 'district_id' => 33, 'name' => 'Umakunda Rural Municipality'],
            ['state_id' => 3, 'district_id' => 33, 'name' => 'Uttar Gaya Rural Municipality'],

            // Sindhuli District
            ['state_id' => 3, 'district_id' => 34, 'name' => 'Kamalamai Municipality'],
            ['state_id' => 3, 'district_id' => 34, 'name' => 'Bhimeshwor Municipality'],
            ['state_id' => 3, 'district_id' => 34, 'name' => 'Baldengadhi Rural Municipality'],
            ['state_id' => 3, 'district_id' => 34, 'name' => 'Golanjor Rural Municipality'],
            ['state_id' => 3, 'district_id' => 34, 'name' => 'Hariharpur Gadhi Rural Municipality'],
            ['state_id' => 3, 'district_id' => 34, 'name' => 'Jogajuli Rural Municipality'],
            ['state_id' => 3, 'district_id' => 34, 'name' => 'Kamalamai Rural Municipality'],
            ['state_id' => 3, 'district_id' => 34, 'name' => 'Kusheshwor Dumja Rural Municipality'],
            ['state_id' => 3, 'district_id' => 34, 'name' => 'Marin Rural Municipality'],
            ['state_id' => 3, 'district_id' => 34, 'name' => 'Ramaroshan Rural Municipality'],
            ['state_id' => 3, 'district_id' => 34, 'name' => 'Sunkoshi Rural Municipality'],
            ['state_id' => 3, 'district_id' => 34, 'name' => 'Tinpatan Rural Municipality'],
            ['state_id' => 3, 'district_id' => 34, 'name' => 'Fikkal Rural Municipality'],
            ['state_id' => 3, 'district_id' => 34, 'name' => 'Gadhi Rural Municipality'],

            // Sindhupalchok District
            ['state_id' => 3, 'district_id' => 35, 'name' => 'Chautara Sangachokgadhi'],
            ['state_id' => 3, 'district_id' => 35, 'name' => 'Bahrabise Municipality'],
            ['state_id' => 3, 'district_id' => 35, 'name' => 'Bhotang Rural Municipality'],
            ['state_id' => 3, 'district_id' => 35, 'name' => 'Chautara Rural Municipality'],
            ['state_id' => 3, 'district_id' => 35, 'name' => 'Dubachaur Rural Municipality'],
            ['state_id' => 3, 'district_id' => 35, 'name' => 'Gati Rural Municipality'],
            ['state_id' => 3, 'district_id' => 35, 'name' => 'Ghyanglefedi Rural Municipality'],
            ['state_id' => 3, 'district_id' => 35, 'name' => 'Gumthang Rural Municipality'],
            ['state_id' => 3, 'district_id' => 35, 'name' => 'Helambu Rural Municipality'],
            ['state_id' => 3, 'district_id' => 35, 'name' => 'Jugal Rural Municipality'],
            ['state_id' => 3, 'district_id' => 35, 'name' => 'Kalika Rural Municipality'],
            ['state_id' => 3, 'district_id' => 35, 'name' => 'Lisankhu Rural Municipality'],
            ['state_id' => 3, 'district_id' => 35, 'name' => 'Majhafed Rural Municipality'],
            ['state_id' => 3, 'district_id' => 35, 'name' => 'Nawalpur Rural Municipality'],
            ['state_id' => 3, 'district_id' => 35, 'name' => 'Panchkhal Rural Municipality'],
            ['state_id' => 3, 'district_id' => 35, 'name' => 'Sangachok Rural Municipality'],
            ['state_id' => 3, 'district_id' => 35, 'name' => 'Selang Rural Municipality'],
            ['state_id' => 3, 'district_id' => 35, 'name' => 'Sunkoshi Rural Municipality'],
            ['state_id' => 3, 'district_id' => 35, 'name' => 'Tatopani Rural Municipality'],
            ['state_id' => 3, 'district_id' => 35, 'name' => 'Thampalkot Rural Municipality'],
            ['state_id' => 3, 'district_id' => 35, 'name' => 'Thambu Rural Municipality'],
            ['state_id' => 3, 'district_id' => 35, 'name' => 'Tripurasundari Rural Municipality'],
            ['state_id' => 3, 'district_id' => 35, 'name' => 'Yamunadhan Rural Municipality'],

            // Kathmandu District
            ['state_id' => 3, 'district_id' => 27, 'name' => 'Kathmandu Metropolitan City'],
            ['state_id' => 3, 'district_id' => 27, 'name' => 'Kageshwori Manohara Municipality'],
            ['state_id' => 3, 'district_id' => 27, 'name' => 'Tokha Municipality'],
            ['state_id' => 3, 'district_id' => 27, 'name' => 'Tarakeshwor Municipality'],
            ['state_id' => 3, 'district_id' => 27, 'name' => 'Dakshinkali Municipality'],
            ['state_id' => 3, 'district_id' => 27, 'name' => 'Chandragiri Municipality'],
            ['state_id' => 3, 'district_id' => 27, 'name' => 'Budhanilkantha Municipality'],
            ['state_id' => 3, 'district_id' => 27, 'name' => 'Gokarneshwor Municipality'],
            ['state_id' => 3, 'district_id' => 27, 'name' => 'Kirtipur Municipality'],
            ['state_id' => 3, 'district_id' => 27, 'name' => 'Shankharapur Municipality'],
            ['state_id' => 3, 'district_id' => 27, 'name' => 'Mahadevsthan Rural Municipality'],
            
            // Lalitpur District
            ['state_id' => 3, 'district_id' => 29, 'name' => 'Lalitpur Metropolitan City'],
            ['state_id' => 3, 'district_id' => 29, 'name' => 'Mahalaxmi Municipality'],
            ['state_id' => 3, 'district_id' => 29, 'name' => 'Godawari Municipality'],
            ['state_id' => 3, 'district_id' => 29, 'name' => 'Konjyosom Rural Municipality'],
            ['state_id' => 3, 'district_id' => 29, 'name' => 'Bagmati Rural Municipality'],
            ['state_id' => 3, 'district_id' => 29, 'name' => 'Lalitpur Rural Municipality'],
            
            // Bhaktapur District
            ['state_id' => 3, 'district_id' => 23, 'name' => 'Bhaktapur Municipality'],
            ['state_id' => 3, 'district_id' => 23, 'name' => 'Suryabinayak Municipality'],
            ['state_id' => 3, 'district_id' => 23, 'name' => 'Changunarayan Municipality'],
            ['state_id' => 3, 'district_id' => 23, 'name' => 'Madhyapur Thimi Municipality'],
            
            // Kavrepalanchok District
            ['state_id' => 3, 'district_id' => 28, 'name' => 'Dhulikhel Municipality'],
            ['state_id' => 3, 'district_id' => 28, 'name' => 'Banepa Municipality'],
            ['state_id' => 3, 'district_id' => 28, 'name' => 'Panauti Municipality'],
            ['state_id' => 3, 'district_id' => 28, 'name' => 'Panchkhal Municipality'],
            ['state_id' => 3, 'district_id' => 28, 'name' => 'Namobuddha Municipality'],
            ['state_id' => 3, 'district_id' => 28, 'name' => 'Khanikhola Rural Municipality'],
            ['state_id' => 3, 'district_id' => 28, 'name' => 'Bhumlung Rural Municipality'],
            ['state_id' => 3, 'district_id' => 28, 'name' => 'Bhumlu Rural Municipality'],
            ['state_id' => 3, 'district_id' => 28, 'name' => 'Bethanchowk Rural Municipality'],
            ['state_id' => 3, 'district_id' => 28, 'name' => 'Mahadevtar Rural Municipality'],
            ['state_id' => 3, 'district_id' => 28, 'name' => 'Made Rural Municipality'],
            ['state_id' => 3, 'district_id' => 28, 'name' => 'Temal Rural Municipality'],
            ['state_id' => 3, 'district_id' => 28, 'name' => 'Koshidekha Rural Municipality'],
            
            // Chitwan District
            ['state_id' => 3, 'district_id' => 24, 'name' => 'Bharatpur Metropolitan City'],
            ['state_id' => 3, 'district_id' => 24, 'name' => 'Ratnanagar Municipality'],
            ['state_id' => 3, 'district_id' => 24, 'name' => 'Khairahani Municipality'],
            ['state_id' => 3, 'district_id' => 24, 'name' => 'Madi Municipality'],
            ['state_id' => 3, 'district_id' => 24, 'name' => 'Kalika Municipality'],
            ['state_id' => 3, 'district_id' => 24, 'name' => 'Rapti Municipality'],
            ['state_id' => 3, 'district_id' => 24, 'name' => 'Ichchhakamana Rural Municipality'],
            ['state_id' => 3, 'district_id' => 24, 'name' => 'Bagauda Rural Municipality'],
            ['state_id' => 3, 'district_id' => 24, 'name' => 'Bharatpur Rural Municipality'],
            
            // Gandaki Province
            // Kaski District
            ['state_id' => 4, 'district_id' => 38, 'name' => 'Pokhara Metropolitan City'],
            ['state_id' => 4, 'district_id' => 38, 'name' => 'Madi Rural Municipality'],
            ['state_id' => 4, 'district_id' => 38, 'name' => 'Rupa Rural Municipality'],
            ['state_id' => 4, 'district_id' => 38, 'name' => 'Bindhyabasini Rural Municipality'],
            ['state_id' => 4, 'district_id' => 38, 'name' => 'Sikles Rural Municipality'],
            ['state_id' => 4, 'district_id' => 38, 'name' => 'Annapurna Rural Municipality'],
            ['state_id' => 4, 'district_id' => 38, 'name' => 'Machhapuchhre Rural Municipality'],
            
            // Syangja District
            ['state_id' => 4, 'district_id' => 45, 'name' => 'Syangja Municipality'],
            ['state_id' => 4, 'district_id' => 45, 'name' => 'Putalibazar Municipality'],
            ['state_id' => 4, 'district_id' => 45, 'name' => 'Waling Municipality'],
            ['state_id' => 4, 'district_id' => 45, 'name' => 'Chapakot Municipality'],
            ['state_id' => 4, 'district_id' => 45, 'name' => 'Galyang Municipality'],
            ['state_id' => 4, 'district_id' => 45, 'name' => 'Biruwa Rural Municipality'],
            ['state_id' => 4, 'district_id' => 45, 'name' => 'Arkhale Rural Municipality'],
            ['state_id' => 4, 'district_id' => 45, 'name' => 'Harinas Rural Municipality'],
            ['state_id' => 4, 'district_id' => 45, 'name' => 'Panchawati Rural Municipality'],
            ['state_id' => 4, 'district_id' => 45, 'name' => 'Khalanga Rural Municipality'],
            ['state_id' => 4, 'district_id' => 45, 'name' => 'Jagat Bhanjyang Rural Municipality'],
            ['state_id' => 4, 'district_id' => 45, 'name' => 'Phedikhola Rural Municipality'],
            
            // Lumbini Province
            // Rupandehi District
            ['state_id' => 5, 'district_id' => 58, 'name' => 'Siddharthanagar Municipality'],
            ['state_id' => 5, 'district_id' => 58, 'name' => 'Butwal Sub-Metropolitan City'],
            ['state_id' => 5, 'district_id' => 58, 'name' => 'Devdaha Municipality'],
            ['state_id' => 5, 'district_id' => 58, 'name' => 'Sainamaina Municipality'],
            ['state_id' => 5, 'district_id' => 58, 'name' => 'Kothiyahi Rural Municipality'],
            ['state_id' => 5, 'district_id' => 58, 'name' => 'Marchawari Rural Municipality'],
            ['state_id' => 5, 'district_id' => 58, 'name' => 'Ayodhyapuri Rural Municipality'],
            ['state_id' => 5, 'district_id' => 58, 'name' => 'Gaidahawa Rural Municipality'],
            ['state_id' => 5, 'district_id' => 58, 'name' => 'Siyari Rural Municipality'],
            ['state_id' => 5, 'district_id' => 58, 'name' => 'Omsatiya Rural Municipality'],
            ['state_id' => 5, 'district_id' => 58, 'name' => 'Parroha Rural Municipality'],
            ['state_id' => 5, 'district_id' => 58, 'name' => 'Sammarimai Rural Municipality'],
            ['state_id' => 5, 'district_id' => 58, 'name' => 'Mayadevi Rural Municipality'],
            ['state_id' => 5, 'district_id' => 58, 'name' => 'Tilottama Municipality'],
            ['state_id' => 5, 'district_id' => 58, 'name' => 'Shivraj Municipality'],
            ['state_id' => 5, 'district_id' => 58, 'name' => 'Kanchan Rural Municipality'],
            ['state_id' => 5, 'district_id' => 58, 'name' => 'Banganga Rural Municipality'],
            ['state_id' => 5, 'district_id' => 58, 'name' => 'Madhavaniya Rural Municipality'],
            
            // Kapilvastu District
            ['state_id' => 5, 'district_id' => 52, 'name' => 'Kapilvastu Municipality'],
            ['state_id' => 5, 'district_id' => 52, 'name' => 'Shivaraj Municipality'],
            ['state_id' => 5, 'district_id' => 52, 'name' => 'Krishnanagar Municipality'],
            ['state_id' => 5, 'district_id' => 52, 'name' => 'Maharajgunj Municipality'],
            ['state_id' => 5, 'district_id' => 52, 'name' => 'Yashodhara Rural Municipality'],
            ['state_id' => 5, 'district_id' => 52, 'name' => 'Bijaynagar Rural Municipality'],
            ['state_id' => 5, 'district_id' => 52, 'name' => 'Suddhodhan Rural Municipality'],
            ['state_id' => 5, 'district_id' => 52, 'name' => 'Bodhaban Rural Municipality'],
            ['state_id' => 5, 'district_id' => 52, 'name' => 'Patari Rural Municipality'],
            ['state_id' => 5, 'district_id' => 52, 'name' => 'Nigdhuvan Rural Municipality'],
            ['state_id' => 5, 'district_id' => 52, 'name' => 'Balarampur Rural Municipality'],
            
            // Karnali Province
            // Surkhet District
            ['state_id' => 6, 'district_id' => 68, 'name' => 'Birendranagar Municipality'],
            ['state_id' => 6, 'district_id' => 68, 'name' => 'Bheri Municipality'],
            ['state_id' => 6, 'district_id' => 68, 'name' => 'Gurvakohol Rural Municipality'],
            ['state_id' => 6, 'district_id' => 68, 'name' => 'Chaukune Rural Municipality'],
            ['state_id' => 6, 'district_id' => 68, 'name' => 'Lekbeshi Rural Municipality'],
            ['state_id' => 6, 'district_id' => 68, 'name' => 'Panchapuri Rural Municipality'],
            ['state_id' => 6, 'district_id' => 68, 'name' => 'Barahatal Rural Municipality'],
            ['state_id' => 6, 'district_id' => 68, 'name' => 'Rajhena Rural Municipality'],
            ['state_id' => 6, 'district_id' => 68, 'name' => 'Chingad Rural Municipality'],
            ['state_id' => 6, 'district_id' => 68, 'name' => 'Dabhe Rural Municipality'],
            
            // Salyan District
            ['state_id' => 6, 'district_id' => 67, 'name' => 'Sharada Municipality'],
            ['state_id' => 6, 'district_id' => 67, 'name' => 'Kalimati Rural Municipality'],
            ['state_id' => 6, 'district_id' => 67, 'name' => 'Kumalakot Rural Municipality'],
            ['state_id' => 6, 'district_id' => 67, 'name' => 'Dhanagadhi Rural Municipality'],
            ['state_id' => 6, 'district_id' => 67, 'name' => 'Bagchaur Rural Municipality'],
            ['state_id' => 6, 'district_id' => 67, 'name' => 'Chhatreshwori Rural Municipality'],
            ['state_id' => 6, 'district_id' => 67, 'name' => 'Shaikhapur Rural Municipality'],
            ['state_id' => 6, 'district_id' => 67, 'name' => 'Kapurkot Rural Municipality'],
            ['state_id' => 6, 'district_id' => 67, 'name' => 'Bhagawatimai Rural Municipality'],
            ['state_id' => 6, 'district_id' => 67, 'name' => 'Damkada Rural Municipality'],
            ['state_id' => 6, 'district_id' => 67, 'name' => 'Tribeni Rural Municipality'],
            
            // Sudurpashchim Province
            // Kailali District
            ['state_id' => 7, 'district_id' => 75, 'name' => 'Dhangadhi Sub-Metropolitan City'],
            ['state_id' => 7, 'district_id' => 75, 'name' => 'Godawari Municipality'],
            ['state_id' => 7, 'district_id' => 75, 'name' => 'Tikapur Municipality'],
            ['state_id' => 7, 'district_id' => 75, 'name' => 'Bhajani Municipality'],
            ['state_id' => 7, 'district_id' => 75, 'name' => 'Janaki Rural Municipality'],
            ['state_id' => 7, 'district_id' => 75, 'name' => 'Joshipur Rural Municipality'],
            ['state_id' => 7, 'district_id' => 75, 'name' => 'Ghodaghodi Municipality'],
            ['state_id' => 7, 'district_id' => 75, 'name' => 'Kailari Rural Municipality'],
            ['state_id' => 7, 'district_id' => 75, 'name' => 'Chure Rural Municipality'],
            ['state_id' => 7, 'district_id' => 75, 'name' => 'Bardagoriya Rural Municipality'],
            ['state_id' => 7, 'district_id' => 75, 'name' => 'Gauriganga Rural Municipality'],
            ['state_id' => 7, 'district_id' => 75, 'name' => 'Masuriya Rural Municipality'],
            ['state_id' => 7, 'district_id' => 75, 'name' => 'Udasipur Rural Municipality'],
            ['state_id' => 7, 'district_id' => 75, 'name' => 'Pachharal Rural Municipality'],
            ['state_id' => 7, 'district_id' => 75, 'name' => 'Shreepur Rural Municipality'],
            ['state_id' => 7, 'district_id' => 75, 'name' => 'Phulbari Rural Municipality'],
            ['state_id' => 7, 'district_id' => 75, 'name' => 'Durgauli Rural Municipality'],
            ['state_id' => 7, 'district_id' => 75, 'name' => 'Api Rural Municipality'],
            
            // Kanchanpur District
            ['state_id' => 7, 'district_id' => 74, 'name' => 'Mahendranagar Municipality'],
            ['state_id' => 7, 'district_id' => 74, 'name' => 'Bedkot Municipality'],
            ['state_id' => 7, 'district_id' => 74, 'name' => 'Belauri Municipality'],
            ['state_id' => 7, 'district_id' => 74, 'name' => 'Beldandi Rural Municipality'],
            ['state_id' => 7, 'district_id' => 74, 'name' => 'Shuklaphanta Municipality'],
            ['state_id' => 7, 'district_id' => 74, 'name' => 'Punarbas Municipality'],
            ['state_id' => 7, 'district_id' => 74, 'name' => 'Bhimdatta Municipality'],
            ['state_id' => 7, 'district_id' => 74, 'name' => 'Krishnapur Municipality'],
            ['state_id' => 7, 'district_id' => 74, 'name' => 'Mahakali Municipality'],
            ['state_id' => 7, 'district_id' => 74, 'name' => 'Sreepur Rural Municipality'],
            ['state_id' => 7, 'district_id' => 74, 'name' => 'Doodhara Chandani Municipality'],
            ['state_id' => 7, 'district_id' => 74, 'name' => 'Parashuram Municipality'],
        ];

        foreach ($municipalities as $municipality) {
            Municipality::create($municipality);
        }
    }
}
